"""empty message

Revision ID: 343e3db5bc3b
Revises: ea227a3adefb
Create Date: 2024-08-12 10:06:13.565535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '343e3db5bc3b'
down_revision = 'ea227a3adefb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('user_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_name_key', ['name'])

    # ### end Alembic commands ###
